const operatingFixedAssets = require("../controllers/operatingFixedAssetsController/operatingFixedAssets");

module.exports = {
  admin: {
    dasboard: {
      create: true,
      read: true,
      update: true,
      delete: true,
    },
    staffUsers: {
      create: true,
      read: true,
      update: true,
      delete: true,
    },
    members: {
      create: true,
      read: true,
      update: true,
      delete: true,
    },
    banks: {
      create: true,
      read: true,
      update: true,
      delete: true,
    },
    fixedAmount: {
      create: true,
      read: true,
      update: true,
      delete: true,
    },
    income: {
      create: true,
      read: true,
      update: true,
      delete: true,
    },
    transferIncome: {
      create: true,
      read: true,
      update: true,
      delete: true,
    },
    bankProfit: {
      create: true,
      read: true,
      update: true,
      delete: true,
    },
    waterMaintenance: {
      create: true,
      read: true,
      update: true,
      delete: true,
    },
    expense: {
      create: true,
      read: true,
      update: true,
      delete: true,
    },
    officeExpense: {
      create: true,
      read: true,
      update: true,
      delete: true,
    },
    siteExpense: {
      create: true,
      read: true,
      update: true,
      delete: true,
    },
    reports: {
      create: true,
      read: true,
      update: true,
      delete: true,
    },
    cashLegder: {
      create: true,
      read: true,
      update: true,
      delete: true,
    },
    bankLeger: {
      create: true,
      read: true,
      update: true,
      delete: true,
    },
    generalLedger: {
      create: true,
      read: true,
      update: true,
      delete: true,
    },
    incomeRecord: {
      create: true,
      read: true,
      update: true,
      delete: true,
    },
    balanceSheet: {
      create: true,
      read: true,
      update: true,
      delete: true,
    },
    apiTester: {
      create: true,
      read: true,
      update: true,
      delete: true,
    },
    operatingFixedAssets: {
      create: true,
      read: true,
      update: true,
      delete: true,
    },
    delistedMembers: {
      create: true,
      read: true,
      update: true,
      delete: true,
    },
  },
  employee: {
    dasboard: {
      create: true,
      read: true,
      update: true,
      delete: true,
    },
    staffUsers: {
      create: false,
      read: false,
      update: false,
      delete: false,
    },
    members: {
      create: false,
      read: true,
      update: false,
      delete: false,
    },
    banks: {
      create: true,
      read: true,
      update: true,
      delete: true,
    },
    fixedAmount: {
      create: false,
      read: false,
      update: false,
      delete: false,
    },
    income: {
      create: true,
      read: true,
      update: true,
      delete: true,
    },
    transferIncome: {
      create: true,
      read: true,
      update: true,
      delete: true,
    },
    bankProfit: {
      create: true,
      read: true,
      update: true,
      delete: true,
    },
    waterMaintenance: {
      create: true,
      read: true,
      update: true,
      delete: true,
    },
    expense: {
      create: true,
      read: true,
      update: true,
      delete: true,
    },
    officeExpense: {
      create: true,
      read: true,
      update: true,
      delete: true,
    },
    siteExpense: {
      create: true,
      read: true,
      update: true,
      delete: true,
    },
    reports: {
      create: true,
      read: true,
      update: true,
      delete: true,
    },
    cashLegder: {
      create: true,
      read: true,
      update: true,
      delete: true,
    },
    bankLeger: {
      create: true,
      read: true,
      update: true,
      delete: true,
    },
    generalLedger: {
      create: true,
      read: true,
      update: true,
      delete: true,
    },
    incomeRecord: {
      create: true,
      read: true,
      update: true,
      delete: true,
    },
    balanceSheet: {
      create: true,
      read: true,
      update: true,
      delete: true,
    },
    apiTester: {
      create: false,
      read: false,
      update: false,
      delete: false,
    },
    operatingFixedAssets: {
      create: true,
      read: true,
      update: true,
      delete: false,
    },
    delistedMembers: {
      create: true,
      read: true,
      update: true,
      delete: false,
    },
  },
};
